version: '2'

services:
    scripts :
        build:
            context: .
        image: file_server
        ports: 
            - 9001:9001
        volumes: 
            - ./:/root/
        depends_on:
            - db
            
    db :
        image: mysql:latest
        restart: always
        volumes: 
            - db_data:/var/lib/mysql/
        environment: 
            MYSQL_ROOT_PASSWORD: password
        expose: 
            - 3306
            
volumes:
    db_data:
